blank_issues_enabled: false

contact_links:
  - name: 💬 Discussions / General Questions
    url: https://github.com/djunekz/termux-app-store/discussions
    about: Use Discussions for general questions, ideas, or non-bug topics.

  - name: 📖 Documentation / Guides
    url: https://github.com/djunekz/termux-app-store/wiki
    about: Read the documentation, installation guide, and usage instructions.

  - name: 🆘 Support / Help / Q & A Discussion
    url: https://github.com/djunekz/termux-app-store/discussions/categories/q-a
    about: Ask for help or troubleshooting support related to Termux App Store.
